tap 'homebrew/cask'

brew 'ack'
brew 'bat'
brew 'diff-so-fancy'
brew 'dnscrypt-proxy'
brew 'fd'
brew 'fnm'
brew 'fzf'
brew 'git'
brew 'git-flow'
brew 'hub'
brew 'mas'
brew 'neovim'
brew 'npm'
brew 'psgrep'
brew 'rbenv'
brew 'rbenv-ctags'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'rg'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tmuxinator'
brew 'tree'
brew 'vim'
brew 'yarn'
brew 'zsh'

cask 'adoptopenjdk'
cask 'brave-browser'
cask 'cheatsheet'
cask 'cyberduck'
cask 'dbeaver-community'
cask 'docker'
cask 'discord'
cask 'firefox'
cask 'fork'
cask 'handbrake'
cask 'iterm2-beta'
cask 'megasync'
cask 'notion'
cask 'postman'
cask 'raycast'
cask 'rescuetime'
cask 'rectangle'
cask 'rowanj-gitx'
cask 'sublime-text'
cask 'superduper'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'

mas 'Guidance', id: 412759995
mas 'LastPass', id: 926036361
mas 'LimeChat', id: 414030210
mas 'Quran Majeed', id: 411622604
mas 'Slack', id: 803453959
mas 'Table Tool', id: 1122008420
mas 'Tailscale', id: 1475387142

